# Generated by Django 3.1.3 on 2024-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0011_auto_20200709_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
